/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BinForecast {
  'forecasts' : Array<DailyForecast>,
  'binId' : BinId,
  'buildingId' : BuildingId,
}
export type BinId = bigint;
export interface BinInfo {
  'id' : BinId,
  'lastCollectedAt' : Timestamp,
  'fillPercent' : bigint,
  'buildingId' : BuildingId,
  'predictedNextCollectionAt' : Timestamp,
  'binLabel' : string,
}
export interface Building {
  'id' : BuildingId,
  'name' : string,
  'zone' : string,
}
export type BuildingId = bigint;
export interface BuildingWasteSummary {
  'rank' : bigint,
  'totalCollectedKg' : bigint,
  'averageFillPercent' : bigint,
  'buildingId' : BuildingId,
  'buildingName' : string,
}
export interface CollectionRecord {
  'status' : CollectionStatus,
  'collectedAt' : Timestamp,
  'fillPercentAtCollection' : bigint,
  'binId' : BinId,
}
export type CollectionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface CollectionTaskInfo {
  'id' : bigint,
  'status' : CollectionStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'binId' : BinId,
}
export type ConfidenceLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface DailyForecast {
  'needsCollection' : boolean,
  'dayOffset' : bigint,
  'predictedFillPercent' : bigint,
  'confidence' : ConfidenceLevel,
}
export type Timestamp = bigint;
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'facilitiesStaff' : null } |
  { 'campusManager' : null };
export interface WasteTrendEntry {
  'dayOffset' : bigint,
  'collectedKg' : bigint,
  'buildingId' : BuildingId,
}
export interface _SERVICE {
  'dispatchCollection' : ActorMethod<[BinId], bigint>,
  'getActiveTasks' : ActorMethod<[], Array<CollectionTaskInfo>>,
  'getBinStatuses' : ActorMethod<[], Array<BinInfo>>,
  'getBinsForBuilding' : ActorMethod<[BuildingId], Array<BinInfo>>,
  'getBinsNeedingCollection' : ActorMethod<[], Array<BinInfo>>,
  'getBuildingForecast' : ActorMethod<[BuildingId], Array<BinForecast>>,
  'getBuildingSummaries' : ActorMethod<[], Array<BuildingWasteSummary>>,
  'getBuildings' : ActorMethod<[], Array<Building>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCollectionHistory' : ActorMethod<[BinId], Array<CollectionRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWasteTrends' : ActorMethod<[], Array<WasteTrendEntry>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCollectionStatus' : ActorMethod<[bigint, CollectionStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];