/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BinId = IDL.Nat;
export const CollectionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CollectionTaskInfo = IDL.Record({
  'id' : IDL.Nat,
  'status' : CollectionStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'binId' : BinId,
});
export const BuildingId = IDL.Nat;
export const BinInfo = IDL.Record({
  'id' : BinId,
  'lastCollectedAt' : Timestamp,
  'fillPercent' : IDL.Nat,
  'buildingId' : BuildingId,
  'predictedNextCollectionAt' : Timestamp,
  'binLabel' : IDL.Text,
});
export const ConfidenceLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const DailyForecast = IDL.Record({
  'needsCollection' : IDL.Bool,
  'dayOffset' : IDL.Nat,
  'predictedFillPercent' : IDL.Nat,
  'confidence' : ConfidenceLevel,
});
export const BinForecast = IDL.Record({
  'forecasts' : IDL.Vec(DailyForecast),
  'binId' : BinId,
  'buildingId' : BuildingId,
});
export const BuildingWasteSummary = IDL.Record({
  'rank' : IDL.Nat,
  'totalCollectedKg' : IDL.Nat,
  'averageFillPercent' : IDL.Nat,
  'buildingId' : BuildingId,
  'buildingName' : IDL.Text,
});
export const Building = IDL.Record({
  'id' : BuildingId,
  'name' : IDL.Text,
  'zone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'facilitiesStaff' : IDL.Null,
  'campusManager' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const CollectionRecord = IDL.Record({
  'status' : CollectionStatus,
  'collectedAt' : Timestamp,
  'fillPercentAtCollection' : IDL.Nat,
  'binId' : BinId,
});
export const WasteTrendEntry = IDL.Record({
  'dayOffset' : IDL.Nat,
  'collectedKg' : IDL.Nat,
  'buildingId' : BuildingId,
});

export const idlService = IDL.Service({
  'dispatchCollection' : IDL.Func([BinId], [IDL.Nat], []),
  'getActiveTasks' : IDL.Func([], [IDL.Vec(CollectionTaskInfo)], ['query']),
  'getBinStatuses' : IDL.Func([], [IDL.Vec(BinInfo)], ['query']),
  'getBinsForBuilding' : IDL.Func([BuildingId], [IDL.Vec(BinInfo)], ['query']),
  'getBinsNeedingCollection' : IDL.Func([], [IDL.Vec(BinInfo)], ['query']),
  'getBuildingForecast' : IDL.Func(
      [BuildingId],
      [IDL.Vec(BinForecast)],
      ['query'],
    ),
  'getBuildingSummaries' : IDL.Func(
      [],
      [IDL.Vec(BuildingWasteSummary)],
      ['query'],
    ),
  'getBuildings' : IDL.Func([], [IDL.Vec(Building)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCollectionHistory' : IDL.Func(
      [BinId],
      [IDL.Vec(CollectionRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWasteTrends' : IDL.Func([], [IDL.Vec(WasteTrendEntry)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCollectionStatus' : IDL.Func([IDL.Nat, CollectionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BinId = IDL.Nat;
  const CollectionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CollectionTaskInfo = IDL.Record({
    'id' : IDL.Nat,
    'status' : CollectionStatus,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'binId' : BinId,
  });
  const BuildingId = IDL.Nat;
  const BinInfo = IDL.Record({
    'id' : BinId,
    'lastCollectedAt' : Timestamp,
    'fillPercent' : IDL.Nat,
    'buildingId' : BuildingId,
    'predictedNextCollectionAt' : Timestamp,
    'binLabel' : IDL.Text,
  });
  const ConfidenceLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DailyForecast = IDL.Record({
    'needsCollection' : IDL.Bool,
    'dayOffset' : IDL.Nat,
    'predictedFillPercent' : IDL.Nat,
    'confidence' : ConfidenceLevel,
  });
  const BinForecast = IDL.Record({
    'forecasts' : IDL.Vec(DailyForecast),
    'binId' : BinId,
    'buildingId' : BuildingId,
  });
  const BuildingWasteSummary = IDL.Record({
    'rank' : IDL.Nat,
    'totalCollectedKg' : IDL.Nat,
    'averageFillPercent' : IDL.Nat,
    'buildingId' : BuildingId,
    'buildingName' : IDL.Text,
  });
  const Building = IDL.Record({
    'id' : BuildingId,
    'name' : IDL.Text,
    'zone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'facilitiesStaff' : IDL.Null,
    'campusManager' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const CollectionRecord = IDL.Record({
    'status' : CollectionStatus,
    'collectedAt' : Timestamp,
    'fillPercentAtCollection' : IDL.Nat,
    'binId' : BinId,
  });
  const WasteTrendEntry = IDL.Record({
    'dayOffset' : IDL.Nat,
    'collectedKg' : IDL.Nat,
    'buildingId' : BuildingId,
  });
  
  return IDL.Service({
    'dispatchCollection' : IDL.Func([BinId], [IDL.Nat], []),
    'getActiveTasks' : IDL.Func([], [IDL.Vec(CollectionTaskInfo)], ['query']),
    'getBinStatuses' : IDL.Func([], [IDL.Vec(BinInfo)], ['query']),
    'getBinsForBuilding' : IDL.Func(
        [BuildingId],
        [IDL.Vec(BinInfo)],
        ['query'],
      ),
    'getBinsNeedingCollection' : IDL.Func([], [IDL.Vec(BinInfo)], ['query']),
    'getBuildingForecast' : IDL.Func(
        [BuildingId],
        [IDL.Vec(BinForecast)],
        ['query'],
      ),
    'getBuildingSummaries' : IDL.Func(
        [],
        [IDL.Vec(BuildingWasteSummary)],
        ['query'],
      ),
    'getBuildings' : IDL.Func([], [IDL.Vec(Building)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCollectionHistory' : IDL.Func(
        [BinId],
        [IDL.Vec(CollectionRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWasteTrends' : IDL.Func([], [IDL.Vec(WasteTrendEntry)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCollectionStatus' : IDL.Func([IDL.Nat, CollectionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };