/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Building {
    id: BuildingId;
    name: string;
    zone: string;
}
export type BuildingId = bigint;
export type BinId = bigint;
export interface CollectionTaskInfo {
    id: bigint;
    status: CollectionStatus;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    binId: BinId;
}
export interface DailyForecast {
    needsCollection: boolean;
    dayOffset: bigint;
    predictedFillPercent: bigint;
    confidence: ConfidenceLevel;
}
export interface BuildingWasteSummary {
    rank: bigint;
    totalCollectedKg: bigint;
    averageFillPercent: bigint;
    buildingId: BuildingId;
    buildingName: string;
}
export interface WasteTrendEntry {
    dayOffset: bigint;
    collectedKg: bigint;
    buildingId: BuildingId;
}
export interface CollectionRecord {
    status: CollectionStatus;
    collectedAt: Timestamp;
    fillPercentAtCollection: bigint;
    binId: BinId;
}
export interface BinForecast {
    forecasts: Array<DailyForecast>;
    binId: BinId;
    buildingId: BuildingId;
}
export interface BinInfo {
    id: BinId;
    lastCollectedAt: Timestamp;
    fillPercent: bigint;
    buildingId: BuildingId;
    predictedNextCollectionAt: Timestamp;
    binLabel: string;
}
export interface UserProfile {
    name: string;
    role: UserRole;
}
export enum CollectionStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ConfidenceLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    facilitiesStaff = "facilitiesStaff",
    campusManager = "campusManager"
}
export interface backendInterface {
    dispatchCollection(binId: BinId): Promise<bigint>;
    getActiveTasks(): Promise<Array<CollectionTaskInfo>>;
    getBinStatuses(): Promise<Array<BinInfo>>;
    getBinsForBuilding(buildingId: BuildingId): Promise<Array<BinInfo>>;
    getBinsNeedingCollection(): Promise<Array<BinInfo>>;
    getBuildingForecast(buildingId: BuildingId): Promise<Array<BinForecast>>;
    getBuildingSummaries(): Promise<Array<BuildingWasteSummary>>;
    getBuildings(): Promise<Array<Building>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCollectionHistory(binId: BinId): Promise<Array<CollectionRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWasteTrends(): Promise<Array<WasteTrendEntry>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCollectionStatus(taskId: bigint, status: CollectionStatus): Promise<void>;
}
import type { BinForecast as _BinForecast, BinId as _BinId, BuildingId as _BuildingId, CollectionRecord as _CollectionRecord, CollectionStatus as _CollectionStatus, CollectionTaskInfo as _CollectionTaskInfo, ConfidenceLevel as _ConfidenceLevel, DailyForecast as _DailyForecast, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async dispatchCollection(arg0: BinId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.dispatchCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dispatchCollection(arg0);
            return result;
        }
    }
    async getActiveTasks(): Promise<Array<CollectionTaskInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTasks();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTasks();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBinStatuses(): Promise<Array<BinInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBinStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBinStatuses();
            return result;
        }
    }
    async getBinsForBuilding(arg0: BuildingId): Promise<Array<BinInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBinsForBuilding(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBinsForBuilding(arg0);
            return result;
        }
    }
    async getBinsNeedingCollection(): Promise<Array<BinInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBinsNeedingCollection();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBinsNeedingCollection();
            return result;
        }
    }
    async getBuildingForecast(arg0: BuildingId): Promise<Array<BinForecast>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildingForecast(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildingForecast(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildingSummaries(): Promise<Array<BuildingWasteSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildingSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildingSummaries();
            return result;
        }
    }
    async getBuildings(): Promise<Array<Building>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildings();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionHistory(arg0: BinId): Promise<Array<CollectionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionHistory(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionHistory(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWasteTrends(): Promise<Array<WasteTrendEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWasteTrends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWasteTrends();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCollectionStatus(arg0: bigint, arg1: CollectionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollectionStatus(arg0, to_candid_CollectionStatus_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollectionStatus(arg0, to_candid_CollectionStatus_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BinForecast_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BinForecast): BinForecast {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionRecord_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionRecord): CollectionRecord {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionStatus): CollectionStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionTaskInfo_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionTaskInfo): CollectionTaskInfo {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ConfidenceLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConfidenceLevel): ConfidenceLevel {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DailyForecast_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyForecast): DailyForecast {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    needsCollection: boolean;
    dayOffset: bigint;
    predictedFillPercent: bigint;
    confidence: _ConfidenceLevel;
}): {
    needsCollection: boolean;
    dayOffset: bigint;
    predictedFillPercent: bigint;
    confidence: ConfidenceLevel;
} {
    return {
        needsCollection: value.needsCollection,
        dayOffset: value.dayOffset,
        predictedFillPercent: value.predictedFillPercent,
        confidence: from_candid_ConfidenceLevel_n12(_uploadFile, _downloadFile, value.confidence)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
}): {
    name: string;
    role: UserRole;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n17(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CollectionStatus;
    collectedAt: _Timestamp;
    fillPercentAtCollection: bigint;
    binId: _BinId;
}): {
    status: CollectionStatus;
    collectedAt: Timestamp;
    fillPercentAtCollection: bigint;
    binId: BinId;
} {
    return {
        status: from_candid_CollectionStatus_n4(_uploadFile, _downloadFile, value.status),
        collectedAt: value.collectedAt,
        fillPercentAtCollection: value.fillPercentAtCollection,
        binId: value.binId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CollectionStatus;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    binId: _BinId;
}): {
    id: bigint;
    status: CollectionStatus;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    binId: BinId;
} {
    return {
        id: value.id,
        status: from_candid_CollectionStatus_n4(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        binId: value.binId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forecasts: Array<_DailyForecast>;
    binId: _BinId;
    buildingId: _BuildingId;
}): {
    forecasts: Array<DailyForecast>;
    binId: BinId;
    buildingId: BuildingId;
} {
    return {
        forecasts: from_candid_vec_n9(_uploadFile, _downloadFile, value.forecasts),
        binId: value.binId,
        buildingId: value.buildingId
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): ConfidenceLevel {
    return "low" in value ? ConfidenceLevel.low : "high" in value ? ConfidenceLevel.high : "medium" in value ? ConfidenceLevel.medium : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    facilitiesStaff: null;
} | {
    campusManager: null;
}): UserRole {
    return "facilitiesStaff" in value ? UserRole.facilitiesStaff : "campusManager" in value ? UserRole.campusManager : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): CollectionStatus {
    return "pending" in value ? CollectionStatus.pending : "completed" in value ? CollectionStatus.completed : "inProgress" in value ? CollectionStatus.inProgress : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollectionTaskInfo>): Array<CollectionTaskInfo> {
    return value.map((x)=>from_candid_CollectionTaskInfo_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollectionRecord>): Array<CollectionRecord> {
    return value.map((x)=>from_candid_CollectionRecord_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BinForecast>): Array<BinForecast> {
    return value.map((x)=>from_candid_BinForecast_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyForecast>): Array<DailyForecast> {
    return value.map((x)=>from_candid_DailyForecast_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CollectionStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollectionStatus): _CollectionStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
}): {
    name: string;
    role: _UserRole;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n24(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    facilitiesStaff: null;
} | {
    campusManager: null;
} {
    return value == UserRole.facilitiesStaff ? {
        facilitiesStaff: null
    } : value == UserRole.campusManager ? {
        campusManager: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollectionStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == CollectionStatus.pending ? {
        pending: null
    } : value == CollectionStatus.completed ? {
        completed: null
    } : value == CollectionStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
